name: Fifth Workflow
on:
  pull_request:
    # Activity Types
    types:
      - opened
    branches:
      - main # main branch
      - dev-* # dev-something  dev-interesting-addition
      - feat/** # feat/something/random/feature
  workflow_dispatch:
  # push:
  #   branches:
  #     - main # main branch
  #     - dev-* # dev-something  dev-interesting-addition
  #     - feat/** # feat/something/random/feature
  #     # paths:
  #     # paths-ignore:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Check Linting
        run: npm run lint
      - name: Check tests
        run: npm run test
      - name: build project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying..."
      - name: Deployed
        run: echo "Deployed."
