name: Fourth Workflow
on:
  issues:
    types:
      - opened
      - closed
  workflow_dispatch:
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issues Event Details
        run: echo "${{toJSON(github.event)}}"
