name: Output Event Details on "issues"
on:
  issues:
    types:
      - opened
jobs:
  Output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Details
        run: echo "${{toJSON(github.event)}}"
