name: Third Workflow
on:
  # push:
  #   branches: main
  workflow_dispatch:
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Check Linting
        run: npm run lint
  testing:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Check Testing
        run: npm run test
  deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Get Github Context
        run: echo "${{toJSON(github)}}"
      - name: Deploying
        run: echo "Deploying..."
      - name: Deployed
        run: echo "Deployed."
